before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: TrdeR1lAcvR8uuGVsdAE9FYjjgRvqWZjdtfb+RBB2IF+2Ux3AWTHvmj5WxxlzJOxvZ8o/ZBVyw+VwBp9lfXqoOKmm3+821kY59KsrJCv9MSbo83o8UnYY3pD/GLnvNcQX6ryOD9WEkubbTw4n4MLNOq3W+rjuc06y6e87lDUUuC+R9U3aRAcvHe1myGi4h8hV2+3NQGlo5MZ57L1yMF1T2mFgqlQXcdqeJMWZBoe4Cz6+Lcnt0pnizCOQoWX/kNDsMHf1UkGwy2eN9wE0d8R1pbOxFtdhsvvBZU1DReOALdEAZkXGZIROPzqw+V2xrvQh5dvqOBoVn2HJu8jIi3PghNpQvmPbTE78U2pSaBorhevJu/L3/gHYwDVxkOn/mUm5SJ8dfNJ2GXViB6T8VnFlok4fCglip8mgD82IWWXnJ3cW+n9Qnbvp6r9exqE8nO7Q4VZG1pPnSKbul/CSrlt+ItkHctT9m3j6/Zr3kyomK13HADSk3oQk3mTIhRJ+b/ogqJeP/TK6G5vvlcEtrnZ/lMagJgRB1LkQvl2hoOmpJeTV2w8j2Y7kNeaHxa8y1ayH4eozVPU0aMdGDPK9+BkQ1I1WOXvoQ33xX7f0RURdreEzkRD+OLTK1F5kTjtPNJrA+k42Cr2umK4dS0sexSJDAAm26U6/fNI5wix4MOhjRA= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
